### PR TITLE
Update perforce-server r15.1 sha

### PR DESCRIPTION
**Pull request by larsxschneider**

### CODE REVIEW

**Comment by dunn** [comment]
The test's failing; might just be that the output has changed: http://bot.brew.sh/job/Homebrew%20Binary%20Pull%20Requests/182/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_homebrew_binary_perforce_server/

**Comment by larsxschneider** [comment]
@dunn Thanks for the hint :+1:

**Comment by dunn** [comment]
Oh, do you know if the Linux source has been updated too?

**Comment by larsxschneider** [comment]
What do you mean by that? I thought brew is only for OS X...

**Comment by dunn** [comment]
Oh, I mean the 32-bit binary: http://filehost.perforce.com/perforce/r15.1/bin.darwin90x86/p4d

The science tap supports Linuxbrew so I got confused there.

**Comment by larsxschneider** [comment]
Is there a way to disable the hash check for a bottle? I guess not... and it's probably not wanted by the maintainer...

The hash I added here is already outdated. Perforce has a continues delivery setup and changes the file every other day. Do you have an idea how we can handle that with brew?

**Comment by dunn** [comment]
One option would be to move it to the head-only repository; it wouldn't need a checksum there.

**Comment by larsxschneider** [comment]
That sounds interesting. Right now I do this ugly stuff:
`
    P4_SERVER_SHA=$(brew fetch --force perforce-server 2>&1 | grep ^SHA256: | cut -d ' ' -f 2)
    P4_SHA=$(brew fetch --force perforce 2>&1 | grep ^SHA256: | cut -d ' ' -f 2)
    sed -E -i.bak "s/sha256 \"[0-9a-f]{64}\"/sha256 \"$P4_SERVER_SHA\"/g" /usr/local/Library/Taps/homebrew/homebrew-binary/perforce-server.rb
    sed -E -i.bak "s/sha256 \"[0-9a-f]{64}\"/sha256 \"$P4_SHA\"/g" /usr/local/Library/Taps/homebrew/homebrew-binary/perforce.rb
    brew install git-lfs perforce-server perforce
`
Can you point me to a head-only binary example? I only found this:
https://github.com/Homebrew/homebrew-head-only/blob/master/opentracker.rb

**Comment by larsxschneider** [comment]
@dunn ping :smile:

**Comment by dunn** [comment]
Oops, forgot about this, sorry!  Since October we've stopped accepting new formula to head-only, because it really isn't a good user experience.  I guess our options are to keep manually updating the checksum here or convince upstream to provide versioned downloads.

**Comment by larsxschneider** [comment]
Well, both options are not really appealing. I don't want to update the checksum every other day (they ship constant minor updates) and don't have any way to change Perforce's deployment process.

Could you consider a special flag to allow head-only formulas? Something along the lines of `brew install --i-know-what-i-am-doing my-formula`?

**Comment by dunn** [comment]
> Could you consider a special flag to allow head-only formulas?

Afraid not; like I said, the way Homebrew works doesn't lend itself well to head-only formulae.

There's always the option of creating your own tap with a head-only version: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

**Comment by Empact** [comment]
See #312

**Comment by DomT4** [comment]
Closing here. It's a known issue at this point, sadly without much of a reasonable recourse. Will happily review any PR that does something we can all agree is a useful step forwards 😅.

**Pull request closed without merging**
