### PR TITLE
kwm version 2.0.3

### PR DESCRIPTION
**Pull request by koekeishiya**
Updated to version 2.0.3.

Changes can be found [here](https://github.com/koekeishiya/kwm/releases)

### CODE REVIEW

**Comment by dominiklohmann** [comment]
May I suggest changing this to additionally install the man page and listing the breaking changes under caveats?

**Comment by koekeishiya** [comment]
> May I suggest changing this to additionally install the man page and listing the breaking changes under caveats?

the man page is probably something that could be added. Changes however is not something that should be included as caveats in my opinion. Kwm does use semantic versioning (from now on, hence why this is 2.x.x) and so the user should be able to determine whether the new version breaks the existing API.

**Comment by dunn** [comment]
> and listing the breaking changes under caveats?

The caveats are only for Homebrew-specific information.

**Comment by dunn** [comment]
Audit failure:
```
        Error: 1 problem in 1 formula
homebrew/binary/kwm:
 * Please set plist_options when using a formula-defined plist.
```
See [`artifactory.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/artifactory.rb) and [`bacula-fd.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bacula-fd.rb) for examples.

**Comment by koekeishiya** [comment]
Added `plist_options`, hopefully I got it right.

**Comment by dunn** [comment]
Thank you! Merged as d31b18aafaf3f03de174e0416b1a91e4eb033346.

**Pull request closed without merging**
