### PR TITLE
New formula: add binary-only formula for jtool.

### PR DESCRIPTION
**Pull request by geoff-codes**
It's a crucial tool for my workflow; I'm sure for others as well.
Should close/supersede #227 as well.

### CODE REVIEW

**Comment by dunn** [comment]
@BrewTestBot test this pleae

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
The fancy version string is causing problems: http://bot.brew.sh/job/Homebrew%20Binary%20Pull%20Requests/291/version=yosemite/testReport/junit/brew-test-bot/yosemite/install___jtool_1_%CE%B5_yosemite_bottle_tar_gz/

Can it be an ASCII string instead?

**Comment by DomT4** [comment]
This should be submitted to https://github.com/caskroom/homebrew-cask now. We're in the process of deprecating this repository.

We'll take existing formula version bumps here whilst migration is ongoing, but we don't really want to add new formulae, apologies. Thank you for the submission to Homebrew nonetheless ❤️.

**Pull request closed without merging**
