### PR TITLE
Added formula for Caddy HTTP server

### PR DESCRIPTION
**Pull request by dpoggi**
https://caddyserver.com

### CODE REVIEW

**Comment by mistydemeo** [comment]
This is open source; could you submit a formula to build this from source instead?

**Comment by dpoggi** [comment]
I noticed a trend of binary formulas for open-source projects written in Go that provide binaries online (Consul, Packer). Interestingly not followed for Terraform, another Hashicorp product, but nonetheless thought I'd give it a shot, at the very least to try and determine the impetus behind the trend.

**Comment by mistydemeo** [comment]
That was our policy before we had standards in place for packaging Go software; these days, we prefer to build it from source. Not all software in this tap has been migrated to building from source in the main repository, but we're not accepting new binary formulae for Go software here where it's practical to build from source. Terraform was submitted more recently than Packer (about a year ago, vs two years ago), so it was after things changed.

**Comment by dpoggi** [comment]
Gotcha, thanks for the info. I'll close this and work on a source formula.

**Comment by mistydemeo** [comment]
Thanks!

**Comment by mholt** [comment]
If brew follows redirects, you can use any of these URLs to get the latest versions: https://github.com/mholt/caddy/issues/46#issuecomment-100501139

But I guess since you verify the checksum you might want to keep the direct link to the version anyway.

**Pull request closed without merging**
