### PR TITLE
shasum for ngrok archives changed again

### PR DESCRIPTION
**Pull request by knarz**
with the latest version

### CODE REVIEW

**Comment by DomT4** [comment]
Ha, I've just realised what's happening here. The upstream link resolves to `https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip` every time regardless of which version you pass to it:

```
curl -L -v -O https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-9.9.9-darwin-amd64.zip
unzip ngrok-9.9.9-darwin-amd64.zip
./ngrok --version
ngrok version 2.1.3
```

That'll be why it breaks every time. Sigh.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-binary/commit/d8129452ebf9cc28fbc64cbfdcf27e9a9d2c39ea. Thank you for your contribution to Homebrew @knarz; we appreciate it! :smiley_cat:

**Comment by croaky** [comment]
Did this issue return? I'm seeing:

```
==> Installing ngrok2 from homebrew/binary

==> Downloading https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-2.1.3-darwin-amd64.zip

Error: SHA256 mismatch
Expected: 863ebc05824329d288977d275d2ab90e554780a053019ae2bbadb317a1abf607
Actual: 63c9aeee01956f2e9627581f78a2e498e3364455240d663ccf7184c86d0fe6e3
Archive: /Users/croaky/Library/Caches/Homebrew/ngrok2-2.1.3.zip
To retry an incomplete download, remove the file above.

Failed in installing ngrok2
```

From running `brew bundle` on:

```
tap "Homebrew/homebrew-binary"
brew "ngrok2"
```

Any debugging suggestions? Thanks for your help!

**Comment by knarz** [comment]
As DomT4 said, the links seems to always resolve to the latest stable version, so the hash changes whenever they update their binary.

**Pull request merged**
