### PR TITLE
Kwm 1.1.4

### PR DESCRIPTION
**Pull request by dominiklohmann**
Update to 1.1.4, changes can be found here: https://github.com/koekeishiya/kwm/releases/tag/v1.1.4

### CODE REVIEW

**Comment by koekeishiya** [comment]
I found a crucial yet small bug that I had to get in there, so I did a force push to the tag.
The provided sha value has to be updated before this merge can take plase. Sorry about that.

**Comment by dominiklohmann** [comment]
I updated the sha value accordingly.

**Comment by dunn** [comment]
Thank you both! Merged as b9763c78d5b8fd84d364c39561554b7c69b8367f.

**Comment by koekeishiya** [comment]
This version is broken for people who have the newest 10.11.4 with the Xcode 7.3 update.
It seems that they are now enforcing Swift applications to perform #available checks when using APIs that are only available above a certain version. This causes the kwm-overlay to fail, and if enabled, will cause Kwm to crash.

There have also been other improvements to Kwm since, so wondering if the best course of action is to just sibmit a new version that fixes this?

**Comment by dunn** [comment]
That'd be great!

**Pull request closed without merging**
