### PR TITLE
Red 0.5.4

### PR DESCRIPTION
**Pull request by dyba**

### CODE REVIEW

**Comment by dyba** [comment]
In [Red's downloads page](http://www.red-lang.org/p/download.html), they provide a specific build for Mac OS X. I imagine we can't rely on the download link because the version for Red will change. What do you recommend in terms of creating a formula that won't break?

**Comment by dyba** [comment]
Or perhaps, I'll just push out a new commit in the future pointing to the updated link for the new version?

**Comment by bfontaine** [comment]
They provide the source on their download page; is there a reason not to use it?

**Comment by mistydemeo** [comment]
It requires a Rebol interpreter to build. Rebol 2.x is closed-source (there was a PR to submit it here in #128), and while Rebol 3 is open source it's still in alpha and hasn't had a versioned release.

**Comment by mistydemeo** [comment]
The test is failing on all platforms; looks like this is taking longer than the 5 minute timeout period we allocate to formula tests.

**Comment by DomT4** [comment]
Closing as dead. Please feel free to file a fresh PR if you're still interested here. Thank you for the submission to Homebrew! ❤️

**Pull request closed without merging**
