### PR TITLE
adobe-air-sdk-flex 18.0.0.180

### PR DESCRIPTION
**Pull request by L2G**

### CODE REVIEW

**Comment by L2G** [comment]
It looks like the CI failures are due to the binaries being linked against OS X's stock OpenSSL library--but this is to be expected from third-party binaries.

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by L2G** [comment]
It looks like something just went wrong on Jenkins that was unrelated to this particular formula.

**Comment by L2G** [comment]
`brew audit --strict` is still failing this because of the linkage to the system OpenSSL library, and I still don't know if I can do anything about that. I don't have the power to tell Adobe how to change their builds. :smile_cat:

**Comment by mistydemeo** [comment]
Not anything we can do - thanks! Adobe will have to change their builds soon enough...

**Pull request closed without merging**
