### PR TITLE
Delete kwm.rb, libspotify.rb and perforce-server.rb

### PR DESCRIPTION
**Pull request by miccal**
@MikeMcQuaid:

The author of `kwm` maintains their own tap - the [README.md](https://github.com/koekeishiya/kwm) states to run `brew install koekeishiya/formulae/kwm`, so I think this can be safely removed.

The homepage for [`libspotify`](https://developer.spotify.com/technologies/libspotify/) states:

> Important! LibSpotify and CocoaLibSpotify are no longer under active development on any platform and are considered deprecated. If you are building applications for iOS or Android, please use the iOS SDK or Android SDK. We hope to be able to provide you with a new library for other platforms.

So I think this one can also be safely removed.

Finally, I have added `perforce-server.rb` to the `perforce.rb` Cask - see [here](https://github.com/caskroom/homebrew-cask/pull/29180), so this one can be removed.

I updated the `tap_migrations.json` for the perforce formulas in my other PR.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> The author of kwm maintains their own tap - the README.md states to run brew install koekeishiya/formulae/kwm, so I think this can be safely removed.

Could you add that to `tap_migrations.rb`? Thanks!

> So I think this one can also be safely removed.
> 
> Finally, I have added perforce-server.rb to the perforce.rb Cask - see here, so this one can be removed.

👍

**Comment by miccal** [comment]
> Could you add that to tap_migrations.rb? Thanks!

So, like this?

```
"kwm": "koekeishiya/formulae/kwm"
```

**Comment by MikeMcQuaid** [comment]
`"kwm": "koekeishiya/formulae" should be sufficient, I think! Thanks!

**Comment by miccal** [comment]
Done in a new PR https://github.com/Homebrew/homebrew-binary/pull/365.

**Pull request closed without merging**
