### PR TITLE
Fixed adobe-air-sdk SHA256 mismatch.

### PR DESCRIPTION
**Pull request by ydesgagn**
Fixed adobe-air-sdk SHA256 mismatch.

### CODE REVIEW

**Comment by bfontaine** [comment]
Please update the version as well (18.0.0.199).

**Comment by ydesgagn** [comment]
Updated build number.

**Comment by mitio** [comment]
The checksum of this download has changed once again.

The current checksum for the [version **18.0.0.199** download](http://airdownload.adobe.com/air/mac/download/18.0/AdobeAIRSDK.tbz2) is:

    6ce96ce97f2a88ccbc06838f30c743c81e05eb8ab0a82216a1da45cbe30f626e

The version and build number remain unchanged: `18.0.0.199` (taken from the `air-sdk-description.xml` file from within the archive).

There's however a newer version, **19.0.0.241** available at this URL:

    http://airdownload.adobe.com/air/mac/download/19.0/AdobeAIRSDK.tbz2

Its SHA256 is as follows:

    c449ed15cd7722d53cd178c4095e0ce2f815b8f544bd40780a652e382156a1b4

When updated, this PR should resolve #265 and obsolete #266.

**Comment by jonongjs** [comment]
This pull request can be closed as it has been superseded by commit 59c590e.

**Pull request closed without merging**
