### PR TITLE
ngrok 2.0.19

### PR DESCRIPTION
**Pull request by createdbypete**
Adding Ngrok 2 binary here [until it can be built from source](https://github.com/inconshreveable/ngrok#ngrok-20).

Provides 64 and 32 bit versions for OSX.

### CODE REVIEW

**Comment by dongcarl** [comment]
Just curious, but is there a reason why this hasn't been merged yet?

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by bfontaine** [comment]
@dongcarl No reason, really. We get a lot of PRs on all repos and sometimes forget some of them :disappointed:

**Comment by bfontaine** [comment]
Thank you @createdbypete for your contribution to Homebrew; we appreciate it! :tada:

**Comment by createdbypete** [comment]
Happy to do it :)

**Pull request closed without merging**
