### PR TITLE
Minikube (New Formula)

### PR DESCRIPTION
**Pull request by tback**

### CODE REVIEW

**Comment by tback** [comment]
Minikube is still in prerelease state (including v0.3.0). Please merge 0.5.0 if you decide to merge it. It will create a local cluster running the latest released version of kubernetes (1.3.0)

**Comment by tback** [comment]
@ltiao tried to get it into brew, also tried compiling it, but failed (out of memory) so here is my PR for minikube. The original PR from ltiao is here: https://github.com/Homebrew/homebrew-core/pull/2417

**Comment by tback** [comment]
Hey guys,

please let me know if I can do anything to get this merged.

**Comment by bdangit** [comment]
👍

**Comment by sykesm** [comment]
@tback Any chance you want to move this over to github.com/caskroom/homebrew-cask? Looks like this tap was formally deprecated with #346 a few days ago.

**Comment by tback** [comment]
I'd love to and I tried already since I followed the deprecation discussion. It just seems that I'm to stupid to create a cask for a single binary: cask seems to assume that everything is a pkg or dmg and I didn't figure out how to do it for this _very_ simple package. :|

**Comment by therealplato** [comment]
+1, found this thread via `brew search minikube`

For future searchers, you can install via https://github.com/kubernetes/minikube/releases until it's brewable

**Comment by DomT4** [comment]
Apologies for the delay here. As @sykesm noted there's been ongoing internal discussions about us deprecating this tap with the Caskroom & Homebrew formally moving closer to each other, so we didn't want to accept something new & then turn around and inform people it wasn't a valid way to install it.

> It just seems that I'm to stupid to create a cask for a single binary: cask seems to assume that everything is a pkg or dmg and I didn't figure out how to do it for this very simple package.

@vitorgalvao Can you offer some advice on this?

**Comment by vitorgalvao** [comment]
> cask seems to assume that everything is a pkg or dmg and I didn't figure out how to do it for this very simple package.

We usually detect the container quite well. This seems to be a naked binary, so if it fails, you need only add [a single line](https://github.com/caskroom/homebrew-cask/blob/42437e5fcd93b1a3c95376794e6d5eee2b096160/Casks/dogestry.rb#L12).

Use that cask as reference. When you submit please use the download from [the github releases](https://github.com/kubernetes/minikube/releases) rather than the one you have here. You may also try to add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md), but one thing at a time.

Add the `container type: :naked` line and submit it, and we can take it from there. See you on hombrew-cask!

**Comment by DomT4** [comment]
Thanks Vitor.

@tback Will close this here & let the move to Cask go forwards. Feel free to prod one of us if anything else is unclear.

**Pull request closed without merging**
