### PR TITLE
mprime 28.7 (new formula)

### PR DESCRIPTION
**Pull request by herrbischoff**
Great Internet Mersenne Prime Search

### CODE REVIEW

**Comment by bfontaine** [comment]
This seems to be available from source: http://www.mersenne.org/ftp_root/gimps/p95v287.source.zip

**Comment by herrbischoff** [comment]
Sure, but trying to build it via included Makefile fails and there appears to be no compilation instructions. Also, it's recommended on the site to download the binary instead of the source.

**Comment by bfontaine** [comment]
What is the failure like? We prefer to build from source when possible.

**Comment by herrbischoff** [comment]
I appear to have figured it out. Kind of tricky because of the missing compile instructions.

You first need to run a Makefile inside the `gwnum` directory to create a library file which is a dependency, then move back into the `macosx64` directory and run the Makefile there.

How would I go about that most elegantly in a formula? A build script running the makes in sequence?

**Comment by bfontaine** [comment]
Just run these in the `install` method. Based on what you wrote something like this should work:
```rb
def install
  system "make", "-C", "gwnum"
  system "make", "-C", "macosx64"
  # ...
end
```

Note that `make -C foo` is equivalent to `cd foo; make; cd -`. So running `make install` in the `bar` directory can be done with `make -C bar install`.

Please ask if you have more questions :smiley:

**Comment by bfontaine** [comment]
Anything new on this?

**Comment by DomT4** [comment]
Closing as dead. Please feel free to file a fresh PR if you're still interested here. Thank you for the submission to Homebrew! ❤️

**Pull request closed without merging**
