### PR TITLE
helion 1.2.0 (new formula)

### PR DESCRIPTION
**Pull request by neilotoole**
Initial commit of a formula for the 'helion' CLI tool  for the HP Helion Development Platform. This is a tool for managing Helion, in a similar vein to Amazon's AWS tools.

### CODE REVIEW

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by DomT4** [comment]
Any interest here still?

**Comment by neilotoole** [comment]
Yes. I'll get back to you after the long weekend.

**Comment by DomT4** [comment]
This should be submitted to https://github.com/caskroom/homebrew-cask now. We're in the process of deprecating this repository.

We'll take existing formula version bumps here whilst migration is ongoing, but we don't really want to add new formulae, apologies. Thank you for the submission to Homebrew nonetheless ❤️.

**Pull request closed without merging**
