### PR TITLE
Add cm3 formula.

### PR DESCRIPTION
**Pull request by FranklinChen**
Critical Mass Modula-3 compiler.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Can this be built from source? It looks like this is open-source.

**Comment by FranklinChen** [comment]
There is a GItHub repository now https://github.com/modula3/cm3.git but as far as I can tell, there is a bootstrap process required in order to build the compiler using an older version of the compiler, and meanwhile, there have not been any official releases on x64 Mac OS X since the 2010 version I submitted from http://modula3.org/

**Comment by FranklinChen** [comment]
Hold this. I just discovered a release page on the GitHub site https://github.com/modula3/cm3/releases/tag/snapshot-darwin-13.4.0-homebrew-0.9.5-2015-05-28

**Comment by FranklinChen** [comment]
I have submitted an issue https://github.com/modula3/cm3/issues/3 inquiring about an official Homebrew formula. Meanwhile, I'm closing this pull request for now.

**Comment by mistydemeo** [comment]
Thank you!

**Pull request closed without merging**
