### PR TITLE
New formulae: Prometheus

### PR DESCRIPTION
**Pull request by anthonygreen**
This is my first contribution to homebrew-binary
Please assist me in correcting any issues with the formulae
Thx

### CODE REVIEW

**Comment by bfontaine** [comment]
Any reason not to build from source?

**Comment by anthonygreen** [comment]
@bfontaine according to their README

> Using the latest production release binary is the recommended way of installing Prometheus.

**Comment by anthonygreen** [comment]
Unfortunately I can't make head nor tail the build failure msg. 
I've tried on my developer workstation and it installs fine.

**Comment by bfontaine** [comment]
We prefer to build from source when we can. This repository is only for closed-source software or exceptionally stuff that’s too complicated to build from source.

Regarding the build error:

* ``A `test do` test block should be added`` means you need to add a `test do` block to test the formula. See e.g. [`rebol-view.rb`](https://github.com/Homebrew/homebrew-binary/blob/master/rebol-view.rb) or [`chronograf.rb`](https://github.com/Homebrew/homebrew-binary/blob/master/chronograf.rb), both in this repo, as well as [the documentation](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#add-a-test-to-the-formula).
* `Description is too long. "name: desc" should be less than 80 characters.` means that the description is too long. `homebrew/binary/prometheus: <the description>` should fit in 80 characters.
* ``12: Trailing whitespace was found`` means there’s a trailing whitespace line 12, i.e. one or more spaces at the end of the line
* ``Non-executables were installed to "/usr/local/Cellar/prometheus/0.17.0/bin"`` means that non-executables were installed in the `bin` directory, which is reserved for executables. They should be installed somewhere else, e.g. in `libexec`.

**Pull request closed without merging**
