### PR TITLE
The Haskell Tool Stack

### PR DESCRIPTION
**Pull request by bjpbakker**
Rationale: provide a binary install for stack so that a system wide ghc
is not necessary to install stack and have stack install ghc.

Basically this is the same as #242 but its test is a bit more serious than `stack --version`.

### CODE REVIEW

**Comment by bjpbakker** [comment]
This PR replaces Homebrew/homebrew#41787

**Comment by mistydemeo** [comment]
GHC 7.10.2 is out now, so it should be possible to build this from source now.

**Comment by bjpbakker** [comment]
Thanks for the heads up. I opened a new PR that builds stack from source (Homebrew/homebrew#41787)

**Comment by mistydemeo** [comment]
Thanks!

**Pull request closed without merging**
