### PR TITLE
Added Kibana Formula

### PR DESCRIPTION
**Pull request by nickwallen**
Added a formula to install Kibana which is part of the ELK or Elasticsearch stack.  There are already brews for Elasticsearch and Logstash.  This will complete the ELK stack in Brew.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Is it not possible to build this from source?

**Comment by nickwallen** [comment]
There are a ton of dependencies in the Node universe that would need to be installed to build Kibana from source.  That was the first approach that I took until I realized how many dependencies there are.

**Comment by nickwallen** [comment]
Let me know if I can do anything else for this.  I am unfamiliar with the process.  Thanks

**Comment by shawnjohnson** [comment]
I would love to see this added!

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by DomT4** [comment]
We have a from-source formula for this in the core. `brew install kibana`.

**Pull request closed without merging**
