### PR TITLE
Update Perforce binaries to 2014.2.978861

### PR DESCRIPTION
**Pull request by toonetown**
The checksums for p4 and p4d are incorrect

### CODE REVIEW

**Comment by tinnet** [comment]
should'n they match the ones in http://filehost.perforce.com/perforce/r14.2/bin.darwin90x86_64/SHA256SUMS
 and
http://filehost.perforce.com/perforce/r14.2/bin.darwin90x86/SHA256SUMS

This is just very weird...

**Comment by toonetown** [comment]
That is odd - the p4d in this pull request match those files, but not the p4 ones. (the original change #177 has incorrect sha sums for both)

**Comment by toonetown** [comment]
And, I just re-downloaded the p4 binaries, and they are now matching the values in the SHA256SUMS files.  Perhaps my ISP (or someone along the way) had a cached value or something...

I will update this pull request with the values from the SHA256SUMS files.

**Comment by toonetown** [comment]
Actually - something odd is still going on...I am getting signature matches on the x86 versions - but not the x86_64 versions (of p4)

**Comment by toonetown** [comment]
AHA!  For some reason the perforce.rb formula are pulling from the *bin.macosx105* and not the *bin.darwin90* location.  

So - this pull request is actually correct - it contains the same values in http://filehost.perforce.com/perforce/r14.2/bin.darwin90x86_64/SHA256SUMS and http://filehost.perforce.com/perforce/r14.2/bin.darwin90x86/SHA256SUMS for p4d, and the values in http://filehost.perforce.com/perforce/r14.2/bin.macosx105x86_64/SHA256SUMS and http://filehost.perforce.com/perforce/r14.2/bin.macosx105x86/SHA256SUMS for p4.

**Comment by toonetown** [comment]
And as to the reasoning for using the macosx version instead of the darwin version - from http://answers.perforce.com/articles/KB_Article/Perforce-Mac-Platform-Notes:

> **Note:** Both the Mac OS X and Darwin CLI can use the pre-2000.2 two-file scheme to handle resource forks. However, the clients handle apple files differently:
> 
> - The Mac OS X CLI syncs apple files into one file with two forks.
> - The Darwin CLI syncs apple files to the client as two files: "file" and "%file".

**Comment by tinnet** [comment]
oh i did not see that difference in the url, damn! :+1:

**Comment by otaran** [comment]
Looks like version has changed as well. Would you update it?

**Comment by otaran** [comment]
Looks like perforce-server version has changed as well (http://www.perforce.com/downloads/Perforce/20-User says it is 2014.2/978861). Would you update the formula?

**Comment by toonetown** [comment]
OK - I have updated the versions of these two - as well as the hashes.  Everything (relating to perforce/perforce-server/perforce-proxy) seems to be working now with this latest pull request.

**Note:** perforce-proxy is still the same version (962050).  I wonder if the incorrect hashes were for version 962050 of the server and the command line client...and that they were updated after the #177 was submitted.

**Comment by otaran** [comment]
@toonetown, I think you are right, and as @tinnet mentioned, it is gonna break on each *.*.z update.

**Comment by toonetown** [comment]
On the plus side, it looks (from looking at their past version history dropdown), that they generally don't do a *.*.z-only update...perhaps this one was an anomaly...

**Comment by otaran** [comment]
I don't think so - I don't see 2014.2.962050 version in dropdown, so we can't say how often do they change build number.

**Comment by toonetown** [comment]
True - I was just (incorrectly) going based off the fact that there was only a single build number for any single major.minor combination...but you are correct.  That doesn't indicate how often they change their build number without changing the major.minor.

Regardless, it is currently broken, and should probably be fixed.  :)

**Comment by toonetown** [comment]
So - is there something else that this pull request is waiting on before it can be merged?

**Comment by uncreative** [comment]
please merge this...

**Comment by RogerThiede** [comment]
Recommend changing the title of this issue to "Update Perforce binaries to 2014.2.978861" to help manage consistency of continually updated binaries.  The SHA256 checksums will change for each release version even though the URL doesn't change.

Alternatively, we could keep the title and re-open this issue "Fix perforce checksums" each time a new release occurs.  It's likely others would still open new issues though.

**Comment by toonetown** [comment]
Still needs to be merged in...

**Comment by RogerThiede** [comment]
@toonetown, Can you confirm the best route for Mac OS X CLI versus the Darwin CLI?  For a typical brew user, is the current choice the ideal choice?

**Comment by toonetown** [comment]
I would say so - the only difference is that the current version preserves resource forks in the files locally, while the Darwin version strips them out.

**Comment by RogerThiede** [comment]
I see now.  Current brew formulas all prefer bin.macosx105x* only if they are available, and resort to bin.darwin90x* if not.

Formula/Cask | Downloads for platform *Macintosh*
------------ | -------------
perforce-server *p4d* | they only provide bin.darwin90x*
*p4v* | they only provide bin.macosx105x*
perforce *p4* | they only provide multiple downloads

**Pull request closed without merging**
