### PR TITLE
Add Formula for minio server.

### PR DESCRIPTION
**Pull request by harshavardhana**
Signed-off-by: Harshavardhana <harsha@minio.io>

### CODE REVIEW

**Comment by tboerger** [comment]
:+1:

**Comment by harshavardhana** [comment]
Is there anyone who takes a call on new formula?  anything pending that needs to be changed on this one?

**Comment by dunn** [comment]
Sorry for the delay!

Our rule for homebrew-binary is that it's for formulae which _can't_ be built from source.  Looks like minio can be, so it should be submitted to homebrew-core and build from source: https://github.com/minio/minio#source

**Comment by harshavardhana** [comment]
> Sorry for the delay!
> 
> Our rule for homebrew-binary is that it's for formulae which can't be built from source. Looks like minio can be, so it should be submitted to homebrew-core and build from source: https://github.com/minio/minio#source

@dunn it is expected to not build minio from source because we provide custom update mechanism, that is why we though it is better for brew to have binary based builds.

**Comment by harshavardhana** [comment]
Let me know @dunn what you think in these scenarios?

**Comment by dunn** [comment]
What I'd prefer is to have it built from source and the auto-updater disabled, as we do with Heroku: https://github.com/Homebrew/homebrew-core/blob/master/Formula/heroku.rb#L17

Other @Homebrew/maintainers may disagree on this one, though.

**Comment by bfontaine** [comment]
> What I'd prefer is to have it built from source and the auto-updater disabled, as we do with Heroku

👍

**Comment by MikeMcQuaid** [comment]
Agreed.

**Comment by DomT4** [comment]
Closing per the above. Will happily review a from-source submission to `homebrew/core` with the autoupdater killed. Thank you nonetheless for the submission here ❤️.

**Pull request closed without merging**
