### PR TITLE
Add binary for aws-vault tool

### PR DESCRIPTION
**Pull request by createdbypete**
> A vault for securely storing and accessing AWS credentials in development environments

The OSX release is code-signed, and you can verify this with `codesign -dvvv aws-vault`.

Since project does not yet appear to have a homebrew presence I thought I would add it.

### CODE REVIEW

**Comment by DomT4** [comment]
It looks like we can build this from source, so would prefer a from-source submission to `homebrew/core`. Feel free to ping into that PR if that's something you're interested in following up on. Thank you nonetheless for your submission to Homebrew ❤️.

**Comment by lox** [comment]
Author of aws-vault here. It's actually pretty important that the codesigned version is used, because it uses OSX keychain APIs and if it's unsigned you are always prompted. Could this be re-opened please?

**Comment by DomT4** [comment]
This tap is deprecated. I'd recommend submitting your project to https://github.com/caskroom/homebrew-cask which binary stuff will be merging into, with the explanation you've just provided.

**Comment by lox** [comment]
Ok, will do.

**Comment by createdbypete** [comment]
Thank @lox since you are the owner do you want to take it from here? If not I'm happy to put another PR together in the appropriate place.

**Pull request closed without merging**
