### PR TITLE
Add shadowsocks go binary installation

### PR DESCRIPTION
**Pull request by athrunsun**
The lightweight go port of shadowsocks, comes with chacha20 and salsa20 support. The protocol is compatible with the origin shadowsocks. Binary installation contains only a single executable file thus very convenient.

### CODE REVIEW

**Comment by dunn** [comment]
If this can be built from source, it should be.

**Comment by athrunsun** [comment]
Hi @dunn, so usually we won't have a formula with binary installation if it can be built from source?
Or can we have both at the same time? Like `shadowsocks-go-local` and `shadowsocks-go-local-binary`?

**Comment by dunn** [comment]
> we won't have a formula with binary installation if it can be built from source?

That's correct, if we can offer a formula built from source, we will, and if so we won't also have a binary version.

**Comment by DomT4** [comment]
Closing per Alex's comments. Would ❤️ a from-source version submitted to `homebrew/core`.

**Pull request closed without merging**
