### PR TITLE
vault 0.1.0 (new formulae)

### PR DESCRIPTION
**Pull request by chiefy**
I assume this goes in here since `Packer` is also here.

### CODE REVIEW

**Comment by mathewpeterson** [comment]
+1 for this

It looks like the build failed because the ```$ vault help``` requires an argument so, its exit code is 1. Maybe try ```$ vault version``` instead?

**Comment by ffung** [comment]
Yes, I made the some Formulae not knowing about this PR and used vault version. I can confirm that works.

**Comment by chiefy** [comment]
@mathewpeterson d'oh - yeah thanks. I changed it to do `vault ---version` for the test. Waiting on Jenkins, but should pass now.

**Comment by mathewpeterson** [comment]
:+1:

**Comment by mistydemeo** [comment]
A source build for this has been submitted in Homebrew/homebrew#39267, so closing this. Thanks!

**Pull request closed without merging**
