### PR TITLE
Added BioInterchange formula

### PR DESCRIPTION
**Pull request by indiedotkim**
Added a formula for the OS X version of [BioInterchange](https://www.codamono.com/biointerchange/).

BioInterchange is a commercial closed-source project, so it cannot be added to Homebrew, but distributing the binary via Homebrew-binary is fine.

For legal things: I am the indie dev behind BioInterchange, so from my point of view I would be excited to see this pull request succeeding.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Thanks for the submission!

I was looking over the license document, and had a couple questions...

There isn't a grant made to allow redistribution of the software. I want to make sure that Homebrew isn't considered to be distributing the software in a way that's not permitted by the license.

How does licensing work for updates? Is `brew upgrade` bringing updated versions desirable, or will that leave some users with a copy they can't run?

**Comment by indiedotkim** [comment]
@mistydemeo Hm. Redistribution is technically not allowed -- if you are a licensee. I do not consider Docker/Homebrew licensees though, because these are distribution channels from which I benefit.

Licensing for updates: patch and minor version updates are free for licensees. That includes trial and peer-review licenses (free of charge). I actually *want* that users get the latest version, because it means that bugs have been fixed and performance improvements have been made. Long story short: it will *not* leave users with copies they cannot run (in fact, that would be a disaster for me).

**Comment by mistydemeo** [comment]
> Long story short: it will not leave users with copies they cannot run (in fact, that would be a disaster for me).

OK, that sounds great then! You mention patch and minor versions; what's the plan for major version bumps?

**Comment by indiedotkim** [comment]
@mistydemeo Technically, it would mean that new licensing terms (and fees) need to be re-negotiated. In that case, an update might break users' software.

In all fairness though, it is more a legal thing, because as developer, I cannot see that happening in the near future. I am just starting out with my company and I am more concerned with pushing updates to customers right now.

Having said that, I also control the licensing server behind the software. I would probably be able to push a new major version, but only enable new features for selected users (those who accepted new terms/conditions). It is a bit theoretical at this point, but it is conceivable that major updates that do not break the software could be implemented...

Is that acceptable?

**Comment by sjackman** [comment]
If BioInterchange is a GUI app (I see a DMG for distribution) I'd recommend sending this formula instead to https://github.com/caskroom/homebrew-cask after which you can
`brew cask install biointerchange`

**Comment by indiedotkim** [comment]
@sjackman It is actually a command-line app. I only create a DMG for folks who are not very familiar with the command line to start with.

**Comment by sjackman** [comment]
In that case send it to Homebrew-science

**Comment by mistydemeo** [comment]
Having it there may be better for you for discoverability than having it in this tap, and homebrew-science is also an official tap.

**Comment by sjackman** [comment]
Homebrew-science supports both Mac and Linux. Please modify the formula to support both architectures. See for example https://github.com/Homebrew/homebrew-science/blob/master/tbl2asn.rb

**Comment by indiedotkim** [comment]
@sjackman I have a look at Homebrew-science. Thanks!

**Pull request closed without merging**
