### PR TITLE
Add formula for helm-classic 0.8.0+f3cafbc

### PR DESCRIPTION
**Pull request by StalkingKillah**
Added formula for helm-classic 0.8.0+f3cafbc

Signed-off-by: Djordje Stojanovic [djordje.stojanovic@shadow-inc.net](mailto:djordje.stojanovic@shadow-inc.net)

### CODE REVIEW

**Comment by dunn** [comment]
Our rule for homebrew-binary is that we only accept formulae that _can't_ be built from source.  It looks like this can: https://github.com/helm/helm-classic

**Comment by StalkingKillah** [comment]
It can be built from source, but as far as I can see, it requires a docker vm.

**Comment by dunn** [comment]
Oh, what a pain.  Would it be possible to build if we add a built-time dependency on Docker?

**Comment by StalkingKillah** [comment]
I could try building it from source, but i think it needlessly complicates the entire process.

**Comment by dunn** [comment]
If you could give it a shot, that'd be great!

**Comment by DomT4** [comment]
This should be submitted to https://github.com/caskroom/homebrew-cask now, if it can't build from source. We're in the process of deprecating this repository.

We'll take existing formula version bumps here whilst migration is ongoing, but we don't really want to add new formulae, apologies. Thank you for the submission to Homebrew nonetheless ❤️.

**Pull request closed without merging**
