### PR TITLE
Migrate several binaries to Cask

### PR DESCRIPTION
**Pull request by miccal**
https://github.com/caskroom/homebrew-cask/pull/29061

https://github.com/caskroom/homebrew-cask/pull/29062

https://github.com/caskroom/homebrew-cask/pull/29063

https://github.com/caskroom/homebrew-cask/pull/29065

### CODE REVIEW

**Comment by miccal** [comment]
@MikeMcQuaid all the Cask PR's have been merged, thanks.

**Comment by miccal** [comment]
@MikeMcQuaid could you please let me know where the files that are moved via `libexec.install` and 
`prefix.install` should be moved to?

Thanks!

**Comment by MikeMcQuaid** [comment]
@miccal It depends on the files. `libexec` files probably shouldn't be installed at all and `prefix` files if they are a `.app` should go to Applications and otherwise probably not be installed. Feel free to CC me on a Cask WIP PR.

Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by miccal** [comment]
Thanks @MikeMcQuaid - the ones remaining seem a bit more complicated than the ones I have already done.

**Comment by MikeMcQuaid** [comment]
@miccal You can omit `chronograph`. Open PRs for the rest and CC me on them all and I'll help. I believe in you 👍!

**Comment by MikeMcQuaid** [comment]
(as there's a Chronograph PR here: https://github.com/Homebrew/homebrew-binary/pull/356)

**Comment by miccal** [comment]
Thanks @MikeMcQuaid, that is very generous of you, especially with how busy your all are with `brew`.

**Comment by MikeMcQuaid** [comment]
@miccal I'd love to see this tap die 😆

**Comment by larsxschneider** [comment]
I used to install `perforce` with this little hack in the core-git CI:
https://github.com/git/git/blob/master/.travis.yml#L78-L90

The hack was necssary because Perforce changed the binary constantly and therefore the SHA1 stored in brew wouldn't match. Does cask solve this issue? How would I install perforce with cask?

Is this OK? :
```
brew tap caskroom/cask
brew cask install perforce
```

**Comment by reitermarkus** [comment]
@larsxschneider, only the second line will also work, since it is auto-tapped.

Also, the cask uses `:no_check` for the checksum, so no need for a hack anymore:
https://github.com/caskroom/homebrew-cask/blob/ae8d73b0385668b3abd69283421d8a0a056ce704/Casks/perforce.rb#L3

**Comment by larsxschneider** [comment]
@reitermarkus Thanks! I proposed that change to Git-core:
https://github.com/larsxschneider/git/commit/ec7106339d

**Pull request merged**
