### PR TITLE
Add Kettle (Pentaho Data Integration)

### PR DESCRIPTION
**Pull request by joshua-rutherford**

### CODE REVIEW

**Comment by mistydemeo** [comment]
Sorry for the delay on this. A few questions...

1) Is the binary content all Java, or are there any x86 binaries?
2) How is this meant to be used? I see that a `.app` bundle is installed in `libexec`, as is the `spoon` launcher script, but not linked publicly. Is this meant to run just as a server?

**Comment by joshua-rutherford** [comment]
No problem, and thanks for looking at it.

1) This is purely java.  If this does not belong in this repository let me know, but since we aren't compiling the source on the machine, I opened this here.
2) I'm only using this for the server functionality but can easily update to get the 'applications' installed too, would you prefer that?

**Comment by mistydemeo** [comment]
> This is purely java. If this does not belong in this repository let me know, but since we aren't compiling the source on the machine, I opened this here.

We typically allow compiled jars in the main repository since, unlike native binaries, there aren't compatibility issues across OS X releases / architectures.

> I'm only using this for the server functionality but can easily update to get the 'applications' installed too, would you prefer that? 

That would be great! If the `kettle` launcher script could be made public, that would be ideal. The .app isn't as important, IMO, though we could also provide that if appropriate.

**Comment by joshua-rutherford** [comment]
This has been moved to the main repo: https://github.com/Homebrew/homebrew/pull/36743

**Pull request closed without merging**
